version: 2
sources:
- name: bronze
  schema: bronze
  tables:
  - name: master_data_gip_30_all_15_blocks_v2
    identifier: master_data_gip_30_all_15_blocks_v2
    description: ''
  - name: Compile_data
    identifier: Compile_data
    description: ''
